export const SkillOptions = {
  TYPESCRIPT: "Typescript",
  EXPRESS: "Express",
  TAILWINDCSS: "Tailwind CSS",
  FIGMA: "Figma",
  ANGULAR: "Angular",
  REACT: "React",
  HTML: "HTML",
  CSS: "CSS",
  NESTJS: "NestJS",
  MONGODB: "MongoDB",
  SQL: "SQL",
  KOTLIN: "Kotlin",
  ANDROID: "Android",
};
